name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter the new version'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Configure Git
        run: |
          git config --global user.email "princeguptacs@gmail.com"
          git config --global user.name "pashlavish"

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Set npm registry and publish with token
        run: |
          npm config set registry https://registry.npmjs.org/
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
